In [33]:
from pandas import read_csv, DataFrame
from os import getcwd
import numpy as np

In [71]:
##########################################################################################
def get_form_data():
    my_file_dir = getcwd() + "\\merged_form_data.csv"
    df = read_csv(my_file_dir)
    return df

##########################################################################################
def get_mean_se_bounds(lst):
    mean = np.mean(lst)
    std_dev = np.std(lst, ddof=1)
    sem = std_dev / np.sqrt(len(lst))
    lower_error = mean - sem
    upper_error = mean + sem
    return mean, lower_error, upper_error

In [5]:
df = get_form_data()
df.head(8)

,pid,condition,difficulty,tlx_mental,tlx_physical,tlx_hurried,tlx_successful,tlx_hard,tlx_insecure,tlx_ave,...,emb_6,emb_ave,owner_ave,agency_ave,gender,age,video_games,mixed_reality,interact_robot,coordination
0,1,A,7.0,15.0,18.0,17.0,18.0,16.0,18.0,17.000000,...,2.0,1.500000,1.5,1.50,Male,25,4,1,1,3
1,1,B,4.0,9.0,11.0,9.0,10.0,10.0,10.0,9.833333,...,6.0,5.166667,5.0,5.25,Male,25,4,1,1,3
2,1,D,2.0,7.0,9.0,7.0,7.0,7.0,7.0,7.333333,...,6.0,5.666667,5.5,5.75,Male,25,4,1,1,3
3,1,C,2.0,5.0,5.0,4.0,2.0,5.0,4.0,4.166667,...,7.0,6.500000,6.5,6.50,Male,25,4,1,1,3
4,2,B,3.0,2.0,12.0,5.0,1.0,9.0,5.0,5.666667,...,6.0,6.166667,5.5,6.50,Female,30,4,3,1,3
5,2,C,1.0,4.0,6.0,4.0,1.0,8.0,3.0,4.333333,...,6.0,6.666667,7.0,6.50,Female,30,4,3,1,3
6,2,A,3.0,8.0,11.0,6.0,1.0,13.0,7.0,7.666667,...,5.0,5.333333,5.0,5.50,Female,30,4,3,1,3
7,2,D,2.0,5.0,5.0,3.0,1.0,12.0,2.0,4.666667,...,6.0,6.333333,6.0,6.50,Female,30,4,3,1,3

In [55]:
TLX_SCALE_NAMES = ['Mental Demand', 'Physical Demand', 'Temporal Demand',
                   'Performance', 'Effort', 'Frustration']
CONDITION_NAMES = {
    'A': 'Baseline',
    'B': 'HumanHorizontal',
    'C': 'HumanVertical',
    'D': 'RobotHorizontal'
}

pid_list = []
cond_list = []
tlx_scale_list = []
tlx_score_list = []

for index, row in df.iterrows():
    pid = row[0]
    cond_key = row[1]
    cond_name = CONDITION_NAMES[cond_key]
    for tlx_idx in range(3, 9):
        pid_list.append(pid)
        cond_list.append(cond_name)
        tlx_scale_list.append(TLX_SCALE_NAMES[tlx_idx-3])
        tlx_score_list.append(row[tlx_idx])

# generate new dataframe
df_dict = {
    "pid": pid_list,
    "condition": cond_list,
    "tlx_item": tlx_scale_list,
    "tlx_score": tlx_score_list
}
plot_df = DataFrame(df_dict)

# write to csv file
plot_df.to_csv("tlx_plotting_data1.csv", index=False)
print(" Successfully written pre-processed data to csv file! \n")

 Successfully written pre-processed data to csv file!

In [73]:
# mean_df = plot_df.groupby(["condition", "tlx_item"]).apply(get_se_bounds).reset_index(drop=True)
# mean_df

cond_list = []
tlx_item_list = []
tlx_mean_list = []
lower_list = []
upper_list = []

for tlx_item in TLX_SCALE_NAMES:
    for cond in list(CONDITION_NAMES.values()):
        
        group = plot_df[(plot_df['tlx_item']==tlx_item) & (plot_df['condition']==cond)]
        tlx_score_list = group['tlx_score'].tolist()
        mean, lower, upper = get_mean_se_bounds(tlx_score_list)
        
        cond_list.append(cond)
        tlx_item_list.append(tlx_item)
        tlx_mean_list.append(mean)
        lower_list.append(lower)
        upper_list.append(upper)

# generate new dataframe
df_dict = {
    "condition": cond_list,
    "tlx_item": tlx_item_list,
    "tlx_mean": tlx_mean_list,
    "lower": lower_list,
    'upper': upper_list
}
plot_df2 = DataFrame(df_dict)

# write to csv file
plot_df2.to_csv("tlx_plotting_data2.csv", index=False)
print(" Successfully written pre-processed data to csv file! \n")

 Successfully written pre-processed data to csv file!